[package]
name = "a121-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3.5"
defmt-rtt = "0.4.0"

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embassy-sync = { git = "https://github.com/embassy-rs/embassy", features = [ "defmt" ] }

tinyrlibc = { version = "*", git = "https://github.com/rust-embedded-community/tinyrlibc", features = ["snprintf", "alloc"], default-features = false }
talc = { version = "4.2", default-features = false, features = ["lock_api"] }
num = { version = "0.4", default-features = false }
spin = "0.9.8"

[build-dependencies]
bindgen = "0.69"
cc = "1.0"

[profile.dev]
lto = true
codegen-units = 1

[profile.release]
debug = 2
codegen-units = 1
