[package]
name = "a121-rs"
description = "Rust driver for the Acconeer A121 radar sensor"
authors = ["Ragarnoy <tiagolernould@gmail.com>"]
keywords = ["embedded", "a121", "radar"]
license = "MIT"
edition = "2021"
version = "0.1.0"
links = "acconeer_a121"
rust-version = "1.75"

[dependencies]
defmt = "0.3.5"
defmt-rtt = "0.4.0"

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embassy-sync = { git = "https://github.com/embassy-rs/embassy", features = [ "defmt" ] }

num = { version = "0.4", default-features = false }
libm = { version = "0.2.8", default-features = false, optional = true }

[build-dependencies]
bindgen = "0.69"
cc = "1.0"

[features]
distance = []
presence = []
libm = ["dep:libm", "num/libm"]
nightly-logger = []

[profile.dev]
lto = true
codegen-units = 1

[profile.release]
debug = 2
codegen-units = 1
lto = true
opt-level = "s"

