[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32L431CBYx --connect-under-reset"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"
ACC_RSS_LIBS={ value = "acc", relative = true }
CPATH="/usr/lib/arm-none-eabi/include:/home/runner/work/a121-rs/a121-rs/include"
