[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Trom_functions.x",
  "-C", "target-feature=-loop",
]
