# This workflow checks whether the library is able to run without the std library (e.g., embedded).
# This entire file should be removed if this crate does not support no-std. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: example-xe125_nightly-sys_gcc
env:
  CPATH: "/usr/lib/arm-none-eabi/include"
  ACC_RSS_LIBS: "/home/runner/work/a121-rs/a121-rs/staticlibs"
  RLIB_PATH: "cortex_m4_gcc/a121-v1.5.0/lib"
    #FTP_U: ${{ secrets.USERNAME }}
    #FTP_P: ${{ secrets.PASSWORD }}
    #FTP_URI: ${{ secrets.FTPURI }}
jobs:
  nostd:
    runs-on: ubuntu-latest
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [thumbv7em-none-eabihf]
    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@nightly
      - name: Install system build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi clang lftp
      - name: rustup target add ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: cd to examples/xe125-nightly and remove config.toml vars
        run: | 
          cd examples/xe125-nightly
          sed -i 's|^CPATH=.*||' .cargo/config.toml
          sed -i 's|^ACC_RSS_LIBS=.*||' .cargo/config.toml
      - name: fetch the libs
        shell: bash
        env:
          FTP_U: ${{ secrets.USERNAME }}
          FTP_P: ${{ secrets.PASSWORD }}
          FTP_URI: ${{ secrets.FTPURI }}
        run: |
          mkdir -p "$ACC_RSS_LIBS"
          echo $FTP_U | wc -c
          echo $FTP_P | wc -c
          echo $FTP_URI | wc -c
          lftp -u "$FTP_U","$FTP_P" "$FTP_URI" -e "mirror --use-pget-n=8 -c $RLIB_PATH $ACC_RSS_LIBS; bye"
      - name: cargo check
        run: cargo check --target ${{ matrix.target }}
