# This workflow checks whether the library is able to run without the std library (e.g., embedded).
# This entire file should be removed if this crate does not support no-std. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: lib_check-sys_arm_gcc
env:
  CPATH="/usr/lib/arm-none-eabi/include"
  REL_ACC_RSS_LIBS="examples/xe125/acc"
jobs:
  nostd:
    runs-on: ubuntu-latest
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [thumbv7em-none-eabihf]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install system arm gcc and clang
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-none-eabi clang
      - name: rustup target add ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: cargo check with acc libs
        run: ACC_RSS_LIBS="$PWD/$REL_ACC_RSS_LIBS" cargo check --target ${{ matrix.target }} --no-default-features
